# Generated by Django 4.2.4 on 2023-09-07 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Away_club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
        migrations.CreateModel(
            name='team_player',
            fields=[
                ('team_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.team')),
            ],
        ),
        migrations.CreateModel(
            name='matchteam',
            fields=[
                ('matchteam_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.match')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.team')),
            ],
        ),
        migrations.CreateModel(
            name='away_team_player',
            fields=[
                ('team_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.team')),
            ],
        ),
        migrations.CreateModel(
            name='away_team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
        migrations.CreateModel(
            name='away_player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
    ]
