# Generated by Django 4.2.4 on 2023-09-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('htmltopdf', '0002_delete_away_club_remove_away_team_club_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='away_club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='away_team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.away_club')),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.club')),
            ],
        ),
        migrations.CreateModel(
            name='team_player',
            fields=[
                ('team_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.team')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('away_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.away_team')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.team')),
            ],
        ),
        migrations.CreateModel(
            name='away_team_player',
            fields=[
                ('team_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.away_team')),
            ],
        ),
        migrations.CreateModel(
            name='away_player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.away_club')),
            ],
        ),
    ]
