# Generated by Django 4.2.4 on 2023-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmltopdf', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='away_club',
            name='image',
            field=models.ImageField(default='defaultawayclub.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='defaultclub.jpg', upload_to='media'),
        ),
    ]
