# Generated by Django 4.2.4 on 2023-09-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmltopdf', '0004_away_club_image_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='away_team_player',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmltopdf.away_player'),
        ),
    ]
