# Generated by Django 4.2.4 on 2023-09-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmltopdf', '0006_match_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='match',
            new_name='fixture',
        ),
    ]
